spring:
  application:
    name: ${PROJECT_NAME}
  config:
    import: "optional:file:.env[.properties]"
  profiles:
    active: ${APP_ENV:dev}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: ${SERVER_PORT}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    tryItOutEnabled: true
    filter: true
    doc-expansion: none
    tags-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}
  chat-id: ${TELEGRAM_CHAT_ID}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL_LOCAL}
    username: ${DB_USERNAME_LOCAL}
    password: ${DB_PASSWORD_LOCAL}
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL_DEV}
    username: ${DB_USERNAME_DEV}
    password: ${DB_PASSWORD_DEV}
---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url: ${DB_URL_QA}
    username: ${DB_USERNAME_QA}
    password: ${DB_PASSWORD_QA}
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL_PROD}
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
